### ISSUE TITLE
Koodikatsemointi

### ISSUE THREAD

**Issue by ossi-hy** [ni-eminen/ReactComponentViewer#2]
Cloned on 3rd of May commit [f5b2eca](https://github.com/ni-eminen/ReactComponentViewer/commit/f5b2eca647378df163871b3e43907d1fba4d9550).

Programs starts fine on the first try and all the tests pass.
The code is perfectly documented with docstrings with no missing functions. Pylinter gives only one warning.

The program seems to function fine, although it allows user to login without username or password. Everything else like adding or rendering components works well.

I had somewhat hard time combing through the code as I'm not really familiar with react or frontend development. The code seems at moments pretty verbose but that seems to be due to verbosity of tkinter library.

The program is split well into different files and classes with each handling clearly separate functionality of the program. I would however argue the `index.py` still contains enough ui code to belong to `ui` package.

The whole login with username and password seems to be client-side only, which makes it pretty useless in a practical sense (malicious user can bypass the code or just read the *components* table as it's not encrypted), but other than that the implementation seems sound with checking against the hash and using salt to strengthen against a brute force attack.

There is little bit of hardcoding/repetition with tkinter widget attributes. Especially argument `bg='white'` can be seen multiple times in all of the ui files. Maybe the common colors and fonts could be defined in some kind of style config, much like CSS in HTML.

In the file `add_component_screen.py` there is global variable `POP` and as it's only referenced inside class `AddComponentScreen` of a which there is only one instance of (?) it could be changed to be a member of `AddComponentScreen` class.

There aren't that many tests currently, but as the application is mostly ui, most of the codebase falls outside of the testing coverage. The tests for the remaining code are well written, focused and self-descriptive.

Overall well written project that is easy to read and understand, and possibly expand.

**Comment by ni-eminen** [comment]
Thanks for the feedback. Tkinter offers a way to bundle styles using its ttk library. I have decided not to use it due to its minimal benefit in this case. The database will be transferred to cloud in the future, but it is not the focus of the related course so I have not had the time to do that. ORM is in place, though, so the migration will be easy.

Thanks for your feedback, I will look into it.
